# Generated by Django 3.1.4 on 2020-12-31 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='foto',
            field=models.ImageField(blank='', null=True, upload_to='imagenes', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='ocupacion',
            field=models.CharField(choices=[('Ingeniero', 'Ingeniero'), ('Abogado', 'Abogado'), ('Independiente', 'independiente')], default='', max_length=50, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='acudiente',
            name='parentesco',
            field=models.CharField(choices=[('Padre', 'Padre'), ('Madre', 'Madre'), ('Hermano', 'Hermano'), ('Tio', 'Tio')], default='', max_length=30, verbose_name='Parentesco'),
        ),
    ]
