# Generated by Django 3.1.4 on 2021-01-17 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20201231_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='foto',
        ),
    ]
