# Generated by Django 3.1.4 on 2020-12-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_auto_20201211_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acudiente',
            name='id_acudiente',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Id Acudiente'),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='id_domicilio',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Id domicilio'),
        ),
        migrations.AlterField(
            model_name='grado',
            name='id_grado',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Id grado'),
        ),
        migrations.AlterField(
            model_name='jornada',
            name='id_jornada',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False, verbose_name='Id jornada'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_pago',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='id pago'),
        ),
    ]
