# Generated by Django 3.1.4 on 2020-12-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0005_auto_20201211_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='id_domicilio',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Id domicilio'),
        ),
    ]
