# Generated by Django 3.1.4 on 2020-12-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0006_auto_20201211_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='id_domicilio',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, unique=True, verbose_name='Id domicilio'),
        ),
    ]
