# Generated by Django 3.1.4 on 2020-12-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0007_auto_20201211_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='id_pago',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id pago'),
        ),
    ]
