# Generated by Django 3.1.4 on 2020-12-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0012_auto_20201211_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='id_pago',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='id pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Banco', 'Banco'), ('Transferencia', 'Tranferencia')], max_length=20, null=True),
        ),
    ]
