# Generated by Django 3.1.4 on 2020-12-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0013_auto_20201211_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='id_docente',
            field=models.CharField(default=5000, max_length=10, primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
