# Generated by Django 3.1.4 on 2020-12-12 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0014_auto_20201211_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jornada',
            name='jornada',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=50, verbose_name='Jornada'),
        ),
    ]
