# Generated by Django 3.1.4 on 2020-12-02 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.SmallIntegerField(verbose_name='Edad'),
        ),
    ]
